template: !include templates.yaml
rest_command: !include rest_commands.yaml
sensor: !include sensors.yaml
shell_command: !include shell_commands.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 3
  auto_purge: true

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

ffmpeg:

homeassistant:
  allowlist_external_dirs:
    - /config/www

# Notification group
notify:
  - platform: group
    name: "ALL_DEVICES"
    services:
      - action: mobile_app_iphone_l
      - action: mobile_app_sreelakshmis_iphone